services:
  # backend is the name of our service
  backend:
    build: ./backend
    # build is used to build the image from the dockerfile. ./backend is the path of the folder that has the dockerfile of backend.
    ports:
      - "8000:3000"
    # ports is used to map the ports . "8000:3000" means host machine's port 8000 is mapped to container's port 3000.
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    # volumes is used to mount the host machine's codebase to the container's codebase. So , if we change the codebase on the host machine, it will automatically be reflected in the container.
    command: npx nodemon -L server.js

volumes:
  backend_node_modules: