import { END, START, StateGraph, StateSchema, type GraphNode , type CompiledStateGraph } from '@langchain/langgraph';
import z from 'zod';
import { geminiModel, cohereModel, mistralAIModel } from './model.ai.js';
import { HumanMessage } from 'langchain';
import { createAgent, providerStrategy } from 'langchain';

const state = new StateSchema({
  problem: z.string().default(''),
  solution_1: z.string().default(''),
  solution_2: z.string().default(''),
  judge: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_reasoning: z.string().default(''),
    solution_2_reasoning: z.string().default(''),
  }),
});

const solutionNode: GraphNode<typeof state> = async (state) => {
  const [mistralResponse, cohereResponse] = await Promise.all([
    mistralAIModel.invoke(state.problem),
    cohereModel.invoke(state.problem),
  ]);

  return {
    solution_1: mistralResponse.text,
    solution_2: cohereResponse.text,
  };
};

/**
 * 

// here, i am using promise.all to invoke both the models in parallel. solutionNode ask for user's problem in the state, and then it will invoke both the models in parallel and return the solution.

// user will provide input in the form of state , state is an object which have problem, solution_1, solution_2, judge. Inside judge , we have solution_1_score, solution_2_score, solution_1_reasoning, solution_2_reasoning. initially our state looks like as below::

// const state = new StateSchema({
    //     problem: z.string().default(""),
    //     solution_1: z.string().default(""),
    //     solution_2: z.string().default(""),
    //     judge:z.object({
        //         solution_1_score: z.number().default(0),
        //         solution_2_score: z.number().default(0),
        //         solution_1_reasoning: z.string().default(""),
        //         solution_2_reasoning: z.string().default(""),
        //     })
        // })
        
        // user will provide the problem inside state as
        // state.problem = "Write a factorial code in JS";
// so, apart from problem property of state, all other properties are empty.
// this state will be passed to the solutionNode
// the typeof solutionNode is GraphNode<typeof state> , this GraphNode expects an argument of type typeof state
// so when we call
// solutionNode(state)
// in solutionNode , we pass the state.problem to mistralAIModel and cohereModel
// thess models works on our problem statement
// it will return the updated state. now in this updated state,
// the solution_1 and solution_2 properties will be filled with the solutions generated by the mistralAIModel and cohereModel respectively.
// apart from solution_1 and solution_2, all other properties will remain same as they were before.

// now this updated state will be passed to the judgeNode.
// the judge will have problem, solution_1 & solution_2 and it will provide solition-1-score, solition-2-score, solution-1-reasoning, solution-2-reasoning.
// it will return updated state.
*/

const judgeNode: GraphNode<typeof state> = async (state) => {
  const { problem, solution_1, solution_2 } = state;

  /**
   * judgeNode has access to problem, solution_1, solution_2 from state
   * we need to compare solution_1 & solution_2 with another AI agent
   *
   * from judge , we need the response in a perticular format as below:
   * {
   * solution_1_score:number(1-10),
   * solution_2_score:number(1-10),
   * solution_1_reasoning:string,
   * solution_2_reasoning:string
   * } if we dont get the response like this , then its quite pointless.
   *
   * so, jab mujhe AI se data proper format main chahiye hota hai, tab mujhe ak agent create karna padta hai aur wo agent mujhe data ak format main deta hain.
   *
   * to create an agent we write as
   * import { createAgent , providerStrategy} from 'langchain';
   *
   * providerStrategy is a function which is used to provide the response format to the agent.
   *
   * NOTE: to create an agent , if we dont use geminiModel but some other model eg: mistal, cohere, gpt, etc. then providerStrategy will not be used. instead we have to use toolStrategy
   */

  const judge = createAgent({
    model: geminiModel,
    responseFormat: providerStrategy(
      z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_reasoning: z.string(),
        solution_2_reasoning: z.string(),
      })
    ),
    systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`,
  });

  /**
   * in the above "judge" we have given system instruction on what to do and how to do. we have told judge on how to generate response:::
   * 
   *   responseFormat: providerStrategy(
      z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_reasoning: z.string(),
        solution_2_reasoning: z.string(),
      })
    ),

    
    /**
     * now we are invoking the judge agent with the problem statement and the solutions generated by the mistralAIModel and cohereModel.
     * the judge agent will provide the response in the format specified by the providerStrategy.
     * the response will be in the form of an object with the following properties:
     * solution_1_score:number(1-10),
     * solution_2_score:number(1-10),
     * solution_1_reasoning:string,
     * solution_2_reasoning:string
     * 
     *  
   */

  const judgeResponse = await judge.invoke({
    messages: [
      new HumanMessage(`
                Problem: ${problem}
                Solution 1: ${solution_1}
                Solution 2: ${solution_2}
                Please evaluate the solutions and provide scores and reasoning.
                `),
    ],
  });

  /**
   * since we are telling to return a response , we will get the response in the form of object with keys solution_1_score, solution_2_score, solution_1_reasoning, solution_2_reasoning
   * this response will only provided in structuredResponse property of judgeResponse
   *
   */
  const {
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning,
  } = judgeResponse.structuredResponse;

  return {
    judge: {
      solution_1_score,
      solution_2_score,
      solution_1_reasoning,
      solution_2_reasoning,
    },
  };
};

/**
 * in langGraph , bydefault there are two nodes, START & END. START node is used to start the graph. END node is used to end the graph.
 * now lets create a graph.
 * 
 */

const graph = new StateGraph(state)
    .addNode("solution", solutionNode)
    .addNode("judge_node", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge_node")
    .addEdge("judge_node", END)
    .compile()


export default async function (problem: string) {
    const result =  await graph.invoke({
        problem: problem
    })

    /**
     * here, our solution node expects a problem from state , we are just invoking the graph with the problem statement. so the START node will only have problem that will so to solutionNode . solutionNode will generate solution_1 , solution_2 . so , along with problem, solution_1 , solution_2 , the entire state will reach the judgeNode. judge will do the needful and end it the final state will come to invoke function as result and we return it.        
     */
    return result;
}