FROM node:20-alpine

# this is the change, add WORKDIR /app and we put the entire code inside /app directory.
WORKDIR /app

COPY package.json /app
COPY package-lock.json /app

RUN npm install

COPY . /app

CMD ["node", "server.js"]
